#include "instances.h"
#include "MRFEnergy.h"

/*
 MRFEnergy<TypeBinary> *a1;
 MRFEnergy<TypeBinaryFast> *a2;
 MRFEnergy<TypePotts> *a3;
 MRFEnergy<TypeGeneral> *a4;
 MRFEnergy<TypeTruncatedLinear> *a5;
 MRFEnergy<TypeTruncatedQuadratic> *a6;
 MRFEnergy<TypeTruncatedLinear2D> *a7;
 MRFEnergy<TypeTruncatedQuadratic2D> *a8;
*/
/*
template class  MRFEnergy<TypeBinary>;
template class MRFEnergy<TypeBinaryFast>;
template class MRFEnergy<TypePotts>;
template class MRFEnergy<TypeGeneral>;
template class MRFEnergy<TypeTruncatedLinear>;
template class MRFEnergy<TypeTruncatedQuadratic>;
template class MRFEnergy<TypeTruncatedLinear2D>;
template class MRFEnergy<TypeTruncatedQuadratic2D>;
*/
